name: My First CI

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Say hello
        run: echo "Hello from GitHub Actions!"
          
      - name: Current datetime
        run: 'echo "Current datetime: $(TZ=Asia/Ho_Chi_Minh date)"'

      - name: Current directory
        run: 'echo "Current directory: $(pwd)"'